name = "bn-worker"
main = "index.js"
compatibility_date = "2024-11-20"
account_id = "d7dcc102dcaa44fb6452f885c35a0b65"

[vars]
# Mock-läge för torrkörning (1 = på, 0 = av)
BN_MOCK_PROVIDERS = "1"
BN_ALLOWED_ORIGIN = "*"
BN_DEFAULT_LANG = "sv"
BN_DEFAULT_WORDS = "800"

# Bindningar
[[d1_databases]]
binding = "DB"
database_name = "BN_DB"
database_id = "från wrangler d1 create BN_DB"

[[kv_namespaces]]
binding = "KV"
id = "från wrangler kv namespace create KV"

[[r2_buckets]]
binding = "R2"
bucket_name = "bn-audio"

[observability]
enabled = true
