# bn-demo/worker/wrangler.toml  — BN 0.4 (Dashboard bindings)
name = "bn-worker"
main = "index.js"
compatibility_date = "2024-11-20"
account_id = "d7dcc102ad44b645f2885c53a0b65"

[vars]
# Mock-läge (1 = mockar LLM/TTS; 0 = riktiga providers)
BN_MOCK_PROVIDERS = "1"
BN_ALLOWED_ORIGIN = "*"
BN_DEFAULT_LANG   = "sv"
BN_DEFAULT_WORDS  = "800"

[observability]
enabled = true
